# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://c0d3cr4f73r.github.io"
# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the repository_name here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)
# repository_name: /personal-jekyll-theme
# Google tracking id
# google-tracking-id: "UA-XXXXXXXX-X"
#############
# HTML Head #
#############
lang: "en"
author: "c0d3cr4f73r"
title: "{ c0d3cr4f73r }"
description: "Blog and website of c0d3cr4f73r, blogging mainly for tech. Opinions expressed are mine."
keywords: "c0d3cr4f73r, personal, redteam, CTF"
favicon: "/img/favicon.ico"
################
# Header layout #
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Infiltrate, adapt, overcome."
  - text: "Exploit the weakness, breach the stronghold."
  - text: "Think like an attacker, defend like a pro."
  - text: "Break barriers, breach defenses."
  - text: "Unleash your cyber prowess, conquer the digital domain."
  - text: "Whereâ€™s your will to be weird?"
me-img: "/img/jetpacktocat.png"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 96
paginate: 8
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True
disqus-shortname: "Personal-Blog"
syntax-highlight: True
############
# Timeline #
############
events:
  - image: "/img/timeline/spidertocat.png"  # Image for Present
    date: "Present"
    description: |
      - Currently serving as a Senior Red Team Operator for the Dubai Government, assessing and fortifying cybersecurity defenses.
      - Actively engaged in sharing knowledge and expertise with the cybersecurity community through blog posts, workshops, and speaking engagements.
  - image: "/img/timeline/baracktocat.jpg"  # Image for 2016 to Present
    date: "2016 to 2019"
    description: |
      - Started professional career as a Red Team Operator at the Sri Lankan Defence Ministry.
      - Continued to enrich experience in offensive security operations at AIX Investment Group in Burj Khalifa, Dubai.
  - image: "/img/timeline/default.png"  # Image for Childhood to University Years
    date: "Childhood to University Years (2008-2015)"
    description: |
      - Explored coding and cybersecurity through CTF games and reverse engineering challenges.
      - Pursued a BSc in Computer Science and participated in local and online CTF competitions.


###########
# Contact #
###########
email: "c0d3cr4f73r@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "c0d3cr4f73r is a cybersecurity enthusiast with a passion for red teaming and malware analysis. 
  Based in Dubai, c0d3cr4f73r has extensive experience in offensive security operations. 
  In their free time, they enjoy diving into the latest cybersecurity challenges."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/c0d3cr4f73r"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com"
  - icon: "x-twitter"
    url: "https://twitter.com/"
  - icon: "rss"
    url: "https://github.com/c0d3cr4f73r/c0d3cr4f73r.github.io/feed.xml"
############
# 404 page #
############
err-404-img: "/img/labtocat.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
